### ISSUE TITLE
Where is the Training Code?

### ISSUE THREAD

**Issue by teapotliid** [xhan77/ssd-lm#1]
I think it is an interesting work and would like to train the SSD-LM. The implementation looks elegant. When will the training code be uploaded?

**Comment by xhan77** [comment]
Hello! We are targeting mid-November for the full code, but I just pushed the main training file we used (`ssd_model_train.py`). We used this file along with a slurm script (coming out later) to train our model.

**Comment by teapotliid** [comment]
Great! Many thanks.
