### ISSUE TITLE
Any plan to release the pretrained diffusion LM?

### ISSUE THREAD

**Issue by baiyuting** [xhan77/ssd-lm#2]
The pretrained diffusion LM outperforms GPT2, it means a lot for diffusion model research in natural language processing. I am interested in using the pretrained diffusion LM on downstream tasks,  I may ask if there is any plan to release the model?  like add the model to Huggingface ?

**Comment by xhan77** [comment]
Thanks for your interest in our work! The model is already pushed to Huggingface's hub (https://huggingface.co/xhan77/ssdlm/tree/main) and can be used according to our demo here: https://colab.research.google.com/drive/1vNKqvzzJQp3k89QPuns5ibsq-VNC9wGN?usp=sharing. In the Colab notebook there are a few helper functions you might want to briefly adapt for your tasks (e.g., generating text with control other than the sentiment classifier in the paper).

**Comment by baiyuting** [comment]
ok, thanks!
